### PR TITLE
enable ios smooth scroll

### PR DESCRIPTION
**Pull request by peaceiris**
1. Add user customizable css file.
    - static/css/custom.css
2. Add `-webkit-overflow-scrolling: touch;` at `custom.css`

### CODE REVIEW

**Comment by xxxtonixxx** [comment]
Why did you close it?

**Comment by peaceiris** [comment]
I'm organizing my Pull Requests that I opened.
I just mistook this repo for my private repo.
Thank you for letting me know.
＼(^o^)／

**Comment by Pilskalns** [comment]
Hi @peaceiris,

There is already a way to create custom CSS/JS files. Please read [this](http://docdock.netlify.com/content-organisation/customize-style/), though I am not sure if it is fully up-to-date and clear.

Also, can `-webkit-overflow-scrolling: touch;` cause issues on other platforms? What about other browser prefixes?

**Comment by peaceiris** [comment]
> There is already a way to create custom CSS/JS files. Please read [this](http://docdock.netlify.com/content-organisation/customize-style/), though I am not sure if it is fully up-to-date and clear.

@Pilskalns 
Thank you for letting me know that information!
Like you say, `static/css/custom.css` will be overwritten by `${hugo_project_root}/static/css/custom.css`.
**We have to use another file name.**

> Also, can `-webkit-overflow-scrolling: touch;` cause issues on other platforms? What about other browser prefixes?

As far as I checked, the following platforms enable momentum scrolling as default and `-webkit-overflow-scrolling: touch;` is safe.

- macOS
  - Safari
  - Chrome
  - Vivaldi
- Android Chrome

But, iOS Safari & iOS Chrome disable momentum scrolling on this theme as default. I think that this is bad usability on iOS devices. So, I sent this PR to enable iOS Chrome & iOS Safari to use momentum scrolling.

**Comment by peaceiris** [comment]
Close this. We need another approach using SCSS and considering "original" and "flex".

**Pull request closed without merging**
