### PR TITLE
Fix the bug #71 through changing the load order of css files.

### PR DESCRIPTION
**Pull request by byzheng**

### CODE REVIEW

**Comment by vjeantet** [comment]
Hello @byzheng,

Adding mermaid on HTML head will slow down page displaying time.

If mermaid has to stay in head, Can you add a defer or async attribute on script tag and check if it resolves your issue ?

**Comment by byzheng** [comment]
Thanks for your suggestions. But don't how to do it. Could you make change? Happy to test it later.

**Comment by vjeantet** [comment]
Ok I'll try on end of week.

Async and Defer are easy and explained here : http://www.growingwiththeweb.com/2014/02/async-vs-defer-attributes.html

**Comment by byzheng** [comment]
Sorry Looks I have mess up this pull request. Will close it as the implementation is not very good too.

**Pull request closed without merging**
