### PR TITLE
Fix caret in menu whitout children

### PR DESCRIPTION
**Pull request by xxxtonixxx**
Hi, this fixes https://github.com/vjeantet/hugo-theme-docdock/issues/36

An image 😉 
image

### CODE REVIEW

**Comment by vjeantet** [comment]
Thanks for this PR !

**Comment by vjeantet** [comment]
hello @xxxtonixxx, stange behavior since this merge

have a look here : https://docdock.netlify.com/shortcodes/children/children-1/children-1-1/

**Comment by xxxtonixxx** [comment]
Hi, good catch! I will fix it 😄

**Comment by vjeantet** [comment]
fixed ! https://github.com/vjeantet/hugo-theme-docdock/commit/8b2384b671ea51276df4bcf98e6df2cb881345a9

**Comment by xxxtonixxx** [comment]
ok @vjeantet Thanks 👍

**Pull request merged**
