### PR TITLE
Plumb in text body divider colour in SCSS.

### PR DESCRIPTION
**Pull request by W-Floyd**
Sorry I haven't been able to do more work on this, I'm in crunch mode, finishing school :/

### CODE REVIEW

**Comment by Pilskalns** [comment]
After this merge I could do splitting that huge file into smaller logical pieces. Changes on `.scss` files would be conflicting with any forks from current state. Anyways, better doing it sooner than later.

**Comment by W-Floyd** [comment]
That would be great! I'll hang fire on any more branches then :)

**Comment by Pilskalns** [comment]
When I did SCSS-breakup branch, I took into account this change.

So I guess this should be cancelled, as there are no more lines where to plug this.

**Comment by W-Floyd** [comment]
Ah, thanks :D

**Pull request closed without merging**
