### PR TITLE
feat: modify attachments to be compatible with pages based on folders

### PR DESCRIPTION
**Pull request by gwleclerc**
now attachements supports:
- content
	- page.files
		- attachment.pdf
	- page.md
	- _index.md

and
- content
	- page
		- index.md
		- files
			- attachment.pdf
	- _index.md

### CODE REVIEW

**Comment by vjeantet** [comment]
Can you update documentation about attachments shortcode ?

Thanks a lot

**Comment by gwleclerc** [comment]
Off course, I can :)
Is that enough to modify exempleSite or there is other changes to do ?

**Comment by vjeantet** [comment]
Only exampleSite

**Comment by gwleclerc** [comment]
done in #10

**Pull request merged**
