### PR TITLE
SCSS breakup

### PR DESCRIPTION
**Pull request by Pilskalns**
Hi @vjeantet, @W-Floyd,

Here's SCSS broken up into logical parts. Tried to keep as few commits as possible. Technically resulted CSS should be doing the same, just order of CSS rules have changed. For example #sidebar has it's own file, because it got so many rules.

There's definitely more to do depending on ambitions, but this should cover foreseeable groundwork to start actually improving things without breaking whole page. 

As far I checked, it looks good and clear, let me know if you find any regressions.

### CODE REVIEW

**Comment by W-Floyd** [comment]
Cool, thanks for going over this!
I'll test shortly.

**Comment by W-Floyd** [comment]
Not that it matters, but do the SCSS files need to be in the static folder? Seeing as browsers can't do anything with them natively.

**Comment by W-Floyd** [comment]
Nothing I'm seeing that's broken, and everything is better than how I had it before.

Might be considered nitpicking , but`$main_link_color` might be better placed in `_colours.scss`. Though currently mapped to `$side_back_color`, that assumes the side is a solid colour and the main background is light. I often have it mapped to its own colour (when running a dark theme), so keeping it with the other primary colours might be useful.

But everything looks good to me!

**Comment by Pilskalns** [comment]
Hi @W-Floyd, sorry for the delay, a lot of work to do. Just feeling like I am missing a reply.

Yes, sure there's a lot to improve, especially, there are a lot of variables, which can make custom styling a little pitty. This was just to kick-off code layout to do that.

Even though SCSS can do complicated styles and layouts with ease, I believe, the goal would that it is possible to create a custom colour theme with simple `theme-custom.css` setting only bg, line, border and foreground colours for **grouped classes** etc. There is something already, but together with SCSS, it is not very transparent. Again, it could be huge work, but very rewarding in long-term.

**Pull request merged**
