### PR TITLE
Transition to SCSS

### PR DESCRIPTION
**Pull request by W-Floyd**
This is where I'll be working with SCSS, in case anyone wants to see it. As is, it's already been made fairly flexible (so far as themeing goes), with only minor tweaking of variables required to fit a given colour scheme. Ideally, I don't want to force any major styling changes on anyone else, so I'll be comparing against default periodically.

Colours are nominally purple themed right now, it changes throughout testing.

### CODE REVIEW

**Comment by W-Floyd** [comment]
Alrighty, as is, unless you're doing something outright weird with the themeing, it'll tend to behave quite nicely when side and body back and text colours are changed.

As can be seen, most variables are some form of the side, back, or text colour modified with an 'lshift' function.
For lack of knowing a better way of doing things, this function shifts lightness (**l**ightness **shift**).

This allows colours to become dark or light depending on their background colour.
Mostly, I use two variants that use back and side colours as their points of reference.
Also importantly, it allows shifting when reference is light or dark separately, though often they'll be the same.

In these functions are also some bias functions, which cause colours (the input, not reference ones) to shift lightness by a greater amount when near mid-grey lightness, because it looks better that way, in my eyes.
At any rate, I've found lshift values require little to no tweaking now this bias is built in.

As an aside, I don't like the function I had to make for the bias, but without non integer powers, it gets tricky to do nicely.
It works well as it sits though, so I can't complain too much.

All used fudge values are declared as variables, so tweaking them is easy.
An overall scaling factor is plumbed in also, though currently not used.
This generally results in increased/reduced contrast, and is best applied sparingly.

I'm still working through this, as I'm using it for some personal project planning.
I still want to try squashing some of the source SCSS down to be a bit DRYer, but I'm still learning my way around CSS in general, let alone a complete project like this.

**Comment by vjeantet** [comment]
@W-Floyd tell me when your code is ready to be merged, so I can read your contribution and merge it

**Comment by W-Floyd** [comment]
I've put the colours back to default and compared against the old theme to verify, so it could probably be merged as is. Existing user restylings will continue to work (so far as I can tell), so no breaking changes should appear.

I still see some issues that will need addressing, namely, providing some complete themes that utilize the SCSS variables.
Buttons are largely unchanged, they could probably react better.
I *might* also look into getting the last 76 (ish?) hardcoded colour values plumbed in appropriately, we'll see.

Those things can probably go into another PR though.

So I'm happy to merge whenever, whatever's easier for you, but only if you're confident in my changes.

I have, unfortunately, not documented some things that I fixed as I went (eg. making bold text actually bold), but hopefully it can be seen what's going on.

Got to go to bed, so I won't be on 'til tomorrow.

**Comment by W-Floyd** [comment]
@vjeantet I'm happy with how it is right now, and my attention is now on the site I'm using the theme with, so feel free to merge whenever. Hopefully I'll get around to plumbing some of the last bits and pieces in later.

**Comment by vjeantet** [comment]
Ok i will review it

**Comment by vjeantet** [comment]
merged :) i had some headaches with menu.html conflicts because of too much whitespaces changes :)

**Comment by W-Floyd** [comment]
Great! Sorry about that, I should have kept my changes more minimal :/

**Comment by Pilskalns** [comment]
Sorry, that regression is on me...

I know this is not place for discussion... but @W-Floyd are you planning on breaking scss file up in multiple files (color theme, layouts, functions, responsive etc.)?

If not, I could take look on it, have also good examples how to organize things.

**Comment by vjeantet** [comment]
Hello @Pilskalns  @W-Floyd 

do you know why sass command returns this error ?
```
$ sass theme.scss test.css
Error: 0.0075/% isn't a valid CSS value.
        on line 270 of theme.scss
  Use --trace for backtrace.
```

I'm using sass version
```
$ sass -v

Sass 3.5.1 (Bleeding Edge)
```

**Comment by Pilskalns** [comment]
I have node-sass, which is required by Atom `sass-autocompile package` and also get such error:

image

```
node-sass       4.5.3   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
```

**Comment by Pilskalns** [comment]
@W-Floyd what `sass` version / compiler are you using? Looks like we use different syntax as the _same_ error pops-out also on other lines.

**Comment by W-Floyd** [comment]
I was using sassc v3.4.5.

I am getting the same error as you with node-sass, so I'll try to get this sorted soon. Sorry about that!

**Comment by W-Floyd** [comment]
@Pilskalns I just noticed the discussion further up.

I had been thinking of splitting things up. Ultimately, it wouldn't change the output any. Feel free to have a poke at that, or I can try later :) Sounds like you have a bit more experience than I do though.

**Comment by vjeantet** [comment]
@Pilskalns thanks again for this PR, a hard work !

**Pull request merged**
