### PR TITLE
feat: automatically scroll to first occurrence of the searched value …

### PR DESCRIPTION
**Pull request by gwleclerc**
…in body-inner

### CODE REVIEW

**Comment by gwleclerc** [comment]
To test it with netlify previews (where search suggestion doesn't work) just type `test` in search input and go to `Create Page -> Present a Slide` the page should scroll to the first occurence.

**Comment by vjeantet** [comment]
Hello, I will have a look tonight

**Comment by vjeantet** [comment]
Hello @gwleclerc ,

if you type `test` go to a page where `test` does not exists an error is thrown and block left right keypress usage

here is the error : 
learn.js:158 Uncaught TypeError: Cannot read property 'scrollIntoView' of undefined
    at HTMLDocument.<anonymous> (learn.js:158)
    at i (jquery-2.x.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.x.min.js:2)
    at Function.ready (jquery-2.x.min.js:2)
    at HTMLDocument.J (jquery-2.x.min.js:2)

**Comment by xxxtonixxx** [comment]
I think the search value should not be saved into sessionStorage, because it will keep there while your moving across the page, then it always will do scrolling if it found the word (a strange behavior). It should be a volatile value like a query parameter or so

**Comment by gwleclerc** [comment]
fixed in #41 
I also agree with @xxxtonixxx but this will need some refact to do it properly.

**Pull request merged**
